In [3]:
import numpy as np

In [5]:
a = np.ones((3,4), dtype=int)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [7]:
b = np.array([3,4,5,1])
print(b)

[3 4 5 1]


In [12]:
# Using broadcasting method to add b  to each row of a

add_row = a + b
print(add_row)

[[4 5 6 2]
 [4 5 6 2]
 [4 5 6 2]]


In [16]:
#To add array of 3*1 to an array of 3*4

c = np.array([[1,2,3]])
d = c.T                    #we convert the array1*3 to array3*1 using transpose

print(c)
print(d)

[[1 2 3]]
[[1]
 [2]
 [3]]


In [18]:
add_column = a + d
print(add_column)

[[2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]


In [22]:
# adding a scaler array to a matrix using broadcasting

e = np.array([1])               #the scaler array
f = a + e
g = b + e

print(f'The scaler e = {e}')
print(f)
print(g)

The scaler e = [1]
[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]
[4 5 6 2]
