In [3]:
# Full Function matrix

import numpy as np

full_mat = np.full((3,4),7)

print(full_mat)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [6]:
full_mat = np.full((6,4),6.3)

print(full_mat)

[[6.3 6.3 6.3 6.3]
 [6.3 6.3 6.3 6.3]
 [6.3 6.3 6.3 6.3]
 [6.3 6.3 6.3 6.3]
 [6.3 6.3 6.3 6.3]
 [6.3 6.3 6.3 6.3]]


In [10]:
# Zeros Function matrix

zero_mat = np.zeros((4,3))

print(zero_mat)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
zero_mat.dtype

dtype('float64')

In [16]:
# To convert the zero function mat from one variabe form to another

zero_mat = np.zeros((4,3), dtype=bool)

print(zero_mat)

[[False False False]
 [False False False]
 [False False False]
 [False False False]]


In [21]:
zero_mat = np.zeros((4,3), dtype=str)

print(zero_mat)

[['' '' '']
 ['' '' '']
 ['' '' '']
 ['' '' '']]


In [26]:
empt_str = ''

print(bool(empt_str))

False


In [32]:
# Ones's function matrix

ones_mat = np.ones((3,3))

print(ones_mat)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [33]:
ones_mat.dtype

dtype('float64')

In [35]:
ones_mat = np.ones((3,3), dtype=bool)          #converting to boolean form

print(ones_mat)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [38]:
ones_mat = np.ones((3,3), dtype=str)

print(ones_mat)

[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]


In [40]:
ones_matc = np.array([[1,1,1],[1,1,1],[1,1,1]])

print(ones_matc)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [42]:
ones_mat = np.ones((3,3), dtype=int)

print(ones_mat)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [48]:
# Eye's function matrix

eye_mat = np.eye(4,4)

print(eye_mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [147]:
# Random function matrix

random_mat = np.random.random((4,3))

print(random_mat)

[[0.920535   0.38867577 0.0821332 ]
 [0.37372875 0.22683452 0.36072369]
 [0.99182401 0.86987603 0.72303218]
 [0.32370902 0.86065452 0.39788005]]


In [69]:
# Empty function matrix

emp_mat1 = np.empty((4,3))

emp_mat1

array([[0.4016372 , 0.72047223, 0.67846441],
       [0.42743742, 0.23505226, 0.221344  ],
       [0.05781606, 0.68544365, 0.2281067 ],
       [0.35500264, 0.05913621, 0.76794514]])

In [72]:
# Functions of Numpy(Arrange function)

a = np.arange(1, 21, 3)    #np.arange(start, end, step) can make a 1D array
print(a)

[ 1  4  7 10 13 16 19]


In [75]:
b = np.arange(1, 21)       #np.arange(start, end)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [145]:
#Lin space function

lin_sp = np.linspace(1, 30, 6)             #np.linspace(start, stop, range)
x = np.linspace(1, 100)
y = x.size
print(lin_sp)
print(x)
print(y)

[ 1.   6.8 12.6 18.4 24.2 30. ]
[  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
  61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
  71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
  81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ]
50


In [83]:
# Reshape function, conversts 1D arrauy into 2D

array_1 = np.arange(1,21)

array_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [86]:
reshape_2D = array_1.reshape(5,4)    #2D array

print(reshape_2D)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [95]:
reshape_3D = array_1.reshape(1, 5, 4)     #3D array

print(reshape_3D)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]
  [17 18 19 20]]]


In [109]:
# Creatin 2D or 3D array using arange function

x = np.arange(1,31).reshape(5,6)      #2D(row, column)
y = np.arange(1,31).reshape(2,3,5)    #3D(section, row, column)

print(x)
print(y)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]


In [114]:
# Ravel function

x.ravel()
y.ravel()


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [119]:
# Flatten function

y.flatten()


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [124]:
# Transpose function

my_value = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(my_value)

#using transpose function
my_value.transpose()

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])