In [3]:
import numpy as np

array_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array_2 = np.array([[11,12,13],[14,15,16],[15,18,19]])

print(array_1)
print(array_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [15 18 19]]


In [9]:
array_3 = np.arange(1,10).reshape(3,3)
array_4 = np.arange(11,20).reshape(3,3)

print(array_3)
print(array_4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [13]:
# Addition of two matrices

a = array_3 + array_4       #using the normal addition meetings
b = np.add(array_3, array_4)

print(a)
print(b)

[[12 14 16]
 [18 20 22]
 [24 26 28]]
[[12 14 16]
 [18 20 22]
 [24 26 28]]


In [16]:
# Sum function of a matrix

np.sum(array_3)               #total number of the whole matrix

45

In [18]:
np.sum(array_3, axis=0)      #the sum of each column to array

array([12, 15, 18])

In [19]:
np.sum(array_3, axis=1)      #the sum of each row to array

array([ 6, 15, 24])

In [24]:
# To subtract two matrices

c = array_3 - array_4
d = np.subtract(array_3, array_4)

print(c)
print(d)

[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]
[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]


In [27]:
# Using division function

e = array_3 / array_4
f = np.divide(array_3,array_4)

print(e)
print(f)

[[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]
 [0.41176471 0.44444444 0.47368421]]
[[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]
 [0.41176471 0.44444444 0.47368421]]


In [30]:
# Mean function of numpy

g = array_3.mean()                        #using mean function
h = np.mean(array_3)                      #using the numpy mean function

print(g)
print(h)

5.0
5.0


In [32]:
np.mean(array_3, axis=0)            #mean of the matrix column

array([4., 5., 6.])

In [34]:
np.mean(array_3, axis=1)            # #mean of the matrix row

array([2., 5., 8.])

In [39]:
# Using Median Numpy function

i = np.median(array_3)

print(i)

#for the axis column and row follow the same pattern as that of the mean

5.0


In [41]:
# Multiplication of two matrices

j = np.multiply(array_3, array_4)   #this is for multiplying the corresponding axis
k = array_3 @ array_4               #using @ functiom
l = array_3.dot(array_4)            #using the .dot multiplication

print(j)
print(k)
print(l)

[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]
[[ 90  96 102]
 [216 231 246]
 [342 366 390]]
[[ 90  96 102]
 [216 231 246]
 [342 366 390]]


In [43]:
# Finding the max, min using the numpy function

array_5 = np.arange(1, 101).reshape(10,10)
print(array_5)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [51]:
m = array_5.min()                        #min of the matrix
n = array_5.max()                        #max of the matrix
o = array_5.argmin()                     #index of the min matrix
p = array_5.argmax()                     #index of the max matrix 
q = array_5.min(axis=0)                  #max of each column
r = array_5.max(axis=1)                  #min of each column

print(m)
print(n)
print(o)
print(p)
print(q)
print(r)

1
100
0
99
[ 1  2  3  4  5  6  7  8  9 10]
[ 10  20  30  40  50  60  70  80  90 100]


In [54]:
# Square root, standard deviation , exponential, longrithmic function

s = np.sqrt(array_3)                 #sqare root function
t = np.std(array_3)                  #standard deviation function
u = np.exp(array_3)                  #exponential function
v = np.log(array_3)                  #longrithmic fuction
w = np.log10(array_3)                #log into base 10 function

print(array_3)
print(s)
print(t)
print(u)
print(v)
print(w)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]
2.581988897471611
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]
[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]
 [0.84509804 0.90308999 0.95424251]]
