In [2]:
import numpy as np

In [14]:
# 1D array

array_1 = np.array([3, 4, 5, 6, 7])

print(array_1)                        #This print the array
print(type(array_1))                  #function to print type of array
array_1.ndim                          #This output the dimension of the array


[3 4 5 6 7]
<class 'numpy.ndarray'>


1

In [16]:
array_1.size                          #This gives the numbers of element in the array

5

In [19]:
array_1.shape                        #This give us the number of rows and shape of the array(rows, columns)
                                     #but for this it only gives us the number of column as row 

(5,)

In [30]:
# 1d array needs 1 index to access each element.

array_1[0], array_1[1], array_1[2], array_1[3], array_1[4]

(3, 4, 5, 6, 7)

In [44]:
# The use of print 

print(array_1[0], array_1[1], array_1[2], array_1[3], array_1[4])

3 4 5 6 7


In [36]:
array_1.dtype                          #finding thw int type of an array


dtype('int32')

In [46]:
#To change the values inside an array

array_1[0] = 20
array_1[-2] = -9

print(array_1)

[20  4  5 -9  7]


In [49]:
# 2D array

array_2 = np.array([[1,4,5,8], [2,5,6,9]])

print(array_2)

[[1 4 5 8]
 [2 5 6 9]]


In [51]:
array_2 = np.array([[1,4,5,8], [2,5,6,9]])

array_2                         #using output tyerminal

array([[1, 4, 5, 8],
       [2, 5, 6, 9]])

In [53]:
array_2.ndim

2

In [55]:
array_2.size

8

In [57]:
array_2.shape 

(2, 4)

In [59]:
array_2.dtype

dtype('int32')

In [63]:
array_2

array([[1, 4, 5, 8],
       [2, 5, 6, 9]])

In [66]:
#Accessing or retrieving 2D array
array_2[1,3]                   #it is in the index of[row, column]             

9

In [68]:
# 3D Array

array_3 = np.array([[[1,4,8,12],[2,5,9,13],[3,6,9,7],[4,7,8,10]]])

print(array_3)

[[[ 1  4  8 12]
  [ 2  5  9 13]
  [ 3  6  9  7]
  [ 4  7  8 10]]]


In [70]:
type(array_3)

numpy.ndarray

In [73]:
print(type(array_3))

<class 'numpy.ndarray'>


In [75]:
array_3.size

16

In [77]:
array_3.ndim

3

In [79]:
array_3.shape

(1, 4, 4)

In [82]:
# 3D Array samp;e

b = np.array([[[1,4,8,12],[2,5,9,13],[4,7,8,10]]])

print(b)

[[[ 1  4  8 12]
  [ 2  5  9 13]
  [ 4  7  8 10]]]


In [83]:
b.shape

(1, 3, 4)