In [5]:
import numpy as np

array_1 = np.arange(101, 201).reshape(10, 10)

print(array_1)

[[101 102 103 104 105 106 107 108 109 110]
 [111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130]
 [131 132 133 134 135 136 137 138 139 140]
 [141 142 143 144 145 146 147 148 149 150]
 [151 152 153 154 155 156 157 158 159 160]
 [161 162 163 164 165 166 167 168 169 170]
 [171 172 173 174 175 176 177 178 179 180]
 [181 182 183 184 185 186 187 188 189 190]
 [191 192 193 194 195 196 197 198 199 200]]


In [24]:
#using the index slicing with comma (',')

a = array_1[0,0]
b = array_1[9,0]
c = array_1[9,9]

#for the dimension number
a1 = array_1[0,0].ndim
b1 = array_1[9,4].ndim
c1 = array_1[9,9].ndim

print(f'Array_1[0,0] is {a} with the dimensional matrix of {a1}')
print(f'Array_1[9,0] is {b} with the dimensional matrix of {b1}')
print(f'Array_1[9,9] is {c} with the dimensional matrix of {c1}' )

Array_1[0,0] is 101 with the dimensional matrix of 0
Array_1[9,0] is 191 with the dimensional matrix of 0
Array_1[9,9] is 200 with the dimensional matrix of 0


In [32]:
# To get a single row

e = array_1[0]
f = array_1[6]

#to get the dimensional of the single row(.ndim)
e1 = array_1[0].ndim
f1 = array_1[6].ndim

print(f'{e} dim:{e1}')
print(f'{f} dim:{f1}')

[101 102 103 104 105 106 107 108 109 110] dim:1
[161 162 163 164 165 166 167 168 169 170] dim:1


In [33]:
# To get a single column

g = array_1[:,0]                  #this give the first column
h = array_1[:,6]                  #this give the sixth column

print(g)
print(h)                          #this gives the answer in form of 1D

[101 111 121 131 141 151 161 171 181 191]
[107 117 127 137 147 157 167 177 187 197]


In [46]:
# Convertion of the column array 1D into 2D

g1 = array_1[:,0:1]             # slicing the column alone
h1 = array_1[:,6:7]             #slicing the column alone

print(g1)
print(h1)

[[101]
 [111]
 [121]
 [131]
 [141]
 [151]
 [161]
 [171]
 [181]
 [191]]
[[107]
 [117]
 [127]
 [137]
 [147]
 [157]
 [167]
 [177]
 [187]
 [197]]


In [51]:
array_1

array([[101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
       [131, 132, 133, 134, 135, 136, 137, 138, 139, 140],
       [141, 142, 143, 144, 145, 146, 147, 148, 149, 150],
       [151, 152, 153, 154, 155, 156, 157, 158, 159, 160],
       [161, 162, 163, 164, 165, 166, 167, 168, 169, 170],
       [171, 172, 173, 174, 175, 176, 177, 178, 179, 180],
       [181, 182, 183, 184, 185, 186, 187, 188, 189, 190],
       [191, 192, 193, 194, 195, 196, 197, 198, 199, 200]])

In [55]:
# To get the slice of matrix

i = array_1[2:5,0:5]              # slicing the rows and column
j = array_1[5:9,:]                # slicing the row alone

print(i)
print(j)

[[121 122 123 124 125]
 [131 132 133 134 135]
 [141 142 143 144 145]]
[[151 152 153 154 155 156 157 158 159 160]
 [161 162 163 164 165 166 167 168 169 170]
 [171 172 173 174 175 176 177 178 179 180]
 [181 182 183 184 185 186 187 188 189 190]]


In [61]:
# To access whole matrix using different functions

#array_1[:]
#array_1[::]
#array_1[:,:]
#array_1[:,0:11]
#array_1[0:11,:]

In [66]:
# Concatenate Function in Numpy

#consider two list addition
list_1 = [5,6,7,8]
list_2 = [4,3,6,5]

m = list_1 + list_2
print(m)

[5, 6, 7, 8, 4, 3, 6, 5]


In [73]:
#using the concatenate function of numpy

array_3 = np.arange(1,21).reshape(4,5)
array_4 = np.arange(21,41).reshape(4,5)

#lets concatenate this array
w = np.concatenate((array_3,array_4), axis=0)  #this concatenate in vertical(column)
x = np.concatenate((array_3,array_4), axis=1)  #this concatenate to horizontal sides(row)

print(w)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]]
[[ 1  2  3  4  5 21 22 23 24 25]
 [ 6  7  8  9 10 26 27 28 29 30]
 [11 12 13 14 15 31 32 33 34 35]
 [16 17 18 19 20 36 37 38 39 40]]


In [83]:
# using another method of function to concatenate the the array

w1 = np.vstack((array_3,array_4))       #for column
x1 = np.hstack((array_3,array_4))       #for row

print(w==w1)
print(x==x1)
    

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[[ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]]
